// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: edge/agent/services/v1/edge_agent_v1_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - edge.agent.services.v1.EdgeAgentService

/// Namespace containing generated types for the "edge.agent.services.v1.EdgeAgentService" service.
public enum Edge_Agent_Services_V1_EdgeAgentService {
    /// Service descriptor for the "edge.agent.services.v1.EdgeAgentService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edge.agent.services.v1.EdgeAgentService")
    /// Namespace for method metadata.
    public enum Method {
        /// Namespace for "RunContainer" metadata.
        public enum RunContainer {
            /// Request type for "RunContainer".
            public typealias Input = Edge_Agent_Services_V1_RunContainerRequest
            /// Response type for "RunContainer".
            public typealias Output = Edge_Agent_Services_V1_RunContainerResponse
            /// Descriptor for "RunContainer".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edge.agent.services.v1.EdgeAgentService"),
                method: "RunContainer"
            )
        }
        /// Descriptors for all methods in the "edge.agent.services.v1.EdgeAgentService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            RunContainer.descriptor
        ]
    }
}

extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "edge.agent.services.v1.EdgeAgentService" service.
    public static let edge_agent_services_v1_EdgeAgentService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edge.agent.services.v1.EdgeAgentService")
}

// MARK: edge.agent.services.v1.EdgeAgentService (server)

extension Edge_Agent_Services_V1_EdgeAgentService {
    /// Streaming variant of the service protocol for the "edge.agent.services.v1.EdgeAgentService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "RunContainer" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Edge_Agent_Services_V1_RunContainerRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Edge_Agent_Services_V1_RunContainerResponse` messages.
        func runContainer(
            request: GRPCCore.StreamingServerRequest<Edge_Agent_Services_V1_RunContainerRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Edge_Agent_Services_V1_RunContainerResponse>
    }

    /// Service protocol for the "edge.agent.services.v1.EdgeAgentService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Edge_Agent_Services_V1_EdgeAgentService.StreamingServiceProtocol {
        /// Handle the "RunContainer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edge_Agent_Services_V1_RunContainerRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Edge_Agent_Services_V1_RunContainerResponse` messages.
        func runContainer(
            request: GRPCCore.ServerRequest<Edge_Agent_Services_V1_RunContainerRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Edge_Agent_Services_V1_RunContainerResponse>
    }

    /// Simple service protocol for the "edge.agent.services.v1.EdgeAgentService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Edge_Agent_Services_V1_EdgeAgentService.ServiceProtocol {
        /// Handle the "RunContainer" method.
        ///
        /// - Parameters:
        ///   - request: A `Edge_Agent_Services_V1_RunContainerRequest` message.
        ///   - response: A response stream of `Edge_Agent_Services_V1_RunContainerResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func runContainer(
            request: Edge_Agent_Services_V1_RunContainerRequest,
            response: GRPCCore.RPCWriter<Edge_Agent_Services_V1_RunContainerResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
extension Edge_Agent_Services_V1_EdgeAgentService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Edge_Agent_Services_V1_EdgeAgentService.Method.RunContainer.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edge_Agent_Services_V1_RunContainerRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Edge_Agent_Services_V1_RunContainerResponse>(),
            handler: { request, context in
                try await self.runContainer(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
extension Edge_Agent_Services_V1_EdgeAgentService.ServiceProtocol {
    public func runContainer(
        request: GRPCCore.StreamingServerRequest<Edge_Agent_Services_V1_RunContainerRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Edge_Agent_Services_V1_RunContainerResponse> {
        let response = try await self.runContainer(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
extension Edge_Agent_Services_V1_EdgeAgentService.SimpleServiceProtocol {
    public func runContainer(
        request: GRPCCore.ServerRequest<Edge_Agent_Services_V1_RunContainerRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Edge_Agent_Services_V1_RunContainerResponse> {
        return GRPCCore.StreamingServerResponse<Edge_Agent_Services_V1_RunContainerResponse>(
            metadata: [:],
            producer: { writer in
                try await self.runContainer(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: edge.agent.services.v1.EdgeAgentService (client)

extension Edge_Agent_Services_V1_EdgeAgentService {
    /// Generated client protocol for the "edge.agent.services.v1.EdgeAgentService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "RunContainer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edge_Agent_Services_V1_RunContainerRequest` message.
        ///   - serializer: A serializer for `Edge_Agent_Services_V1_RunContainerRequest` messages.
        ///   - deserializer: A deserializer for `Edge_Agent_Services_V1_RunContainerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func runContainer<Result>(
            request: GRPCCore.ClientRequest<Edge_Agent_Services_V1_RunContainerRequest>,
            serializer: some GRPCCore.MessageSerializer<Edge_Agent_Services_V1_RunContainerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edge_Agent_Services_V1_RunContainerResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edge_Agent_Services_V1_RunContainerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "edge.agent.services.v1.EdgeAgentService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "RunContainer" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edge_Agent_Services_V1_RunContainerRequest` message.
        ///   - serializer: A serializer for `Edge_Agent_Services_V1_RunContainerRequest` messages.
        ///   - deserializer: A deserializer for `Edge_Agent_Services_V1_RunContainerResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func runContainer<Result>(
            request: GRPCCore.ClientRequest<Edge_Agent_Services_V1_RunContainerRequest>,
            serializer: some GRPCCore.MessageSerializer<Edge_Agent_Services_V1_RunContainerRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edge_Agent_Services_V1_RunContainerResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edge_Agent_Services_V1_RunContainerResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Edge_Agent_Services_V1_EdgeAgentService.Method.RunContainer.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
extension Edge_Agent_Services_V1_EdgeAgentService.ClientProtocol {
    /// Call the "RunContainer" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edge_Agent_Services_V1_RunContainerRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func runContainer<Result>(
        request: GRPCCore.ClientRequest<Edge_Agent_Services_V1_RunContainerRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edge_Agent_Services_V1_RunContainerResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.runContainer(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edge_Agent_Services_V1_RunContainerRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edge_Agent_Services_V1_RunContainerResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
extension Edge_Agent_Services_V1_EdgeAgentService.ClientProtocol {
    /// Call the "RunContainer" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func runContainer<Result>(
        _ message: Edge_Agent_Services_V1_RunContainerRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edge_Agent_Services_V1_RunContainerResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edge_Agent_Services_V1_RunContainerRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.runContainer(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}