# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        swift: ["6.0.3"]
    steps:
    - uses: swift-actions/setup-swift@96e1dd40c7aa863eafac5979fd597972980a64c7
      with:
        swift-version: ${{ matrix.swift }}
    - uses: actions/checkout@v4
    - name: Build CLI
      run: swift build --target edge -v
    - name: Get binary path
      id: get-binary
      run: |
        echo "BINARY_PATH=$(swift build --show-bin-path)/edge" >> $GITHUB_ENV
    - name: Upload binary artifact
      id: upload-artifact
      uses: actions/upload-artifact@v4
      with:
        name: edge-cli-${{ matrix.os }}
        path: ${{ env.BINARY_PATH }}
        retention-days: 14
        if-no-files-found: error
    - name: Output download info
      run: |
        echo "::notice::Binary artifact uploaded with ID: ${{ steps.upload-artifact.outputs.artifact-id }}"
        echo "::notice::Download URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

